INSERT INTO USERS (CREATED_AT, UPDATED_AT, EMAIL, IS_ACTIVE, LAST_MEETUP_AT, NAME) VALUES
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'thtkhanh@gmail.com', true, '1970-01-01 00:00:00', 'Khanh'),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'vuphuong245@gmail.com', true, '1970-01-01 00:00:00', 'Phuong'),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'greatleaf3105@yahoo.com', true, '1970-01-01 00:00:00', 'Diep'),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'hellomy9@hotmail.com', true, '1970-01-01 00:00:00', 'Thanh');

INSERT INTO TIMESLOTS (CREATED_AT, UPDATED_AT, DAY_OF_WEEK, HHMM) VALUES
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 4, '16:30'),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 5, '16:00');

INSERT INTO PREFERENCES (CREATED_AT, UPDATED_AT, TIMESLOT_ID, USER_ID) VALUES
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 1),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 2),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 2),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 3);
